import sys
import os
import json
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from sqlalchemy.orm import Session
from app.db.session import SessionLocal
from app.models import DailyScenario
from datetime import datetime

data_json = """
[
  {
    "id": 91,
    "domain": "Full Stack",
    "day_number": 1,
    "step_number": 1,
    "scenario_text": "You are assigned to build a task management web application. The team asks you to understand the complete frontend, backend, and database workflow before coding.",
    "question_text": "What should you do first?",
    "choice_a_text": "Understand the requirements and identify the frontend, backend, and database responsibilities.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Understanding the complete application flow prevents confusion and helps you plan the architecture correctly.",
    "choice_a_next_scenario_id": 92,
    "choice_b_text": "Start writing frontend components immediately without checking the requirements.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Starting quickly may produce progress, but unclear requirements can cause rework later.",
    "choice_b_next_scenario_id": 92,
    "choice_c_text": "Choose random technologies and begin coding without planning.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Technology choices should be based on project requirements, team skills, and scalability needs.",
    "choice_c_next_scenario_id": 92,
    "is_active": true
  },
  {
    "id": 92,
    "domain": "Full Stack",
    "day_number": 2,
    "step_number": 1,
    "scenario_text": "Your team needs to select a technology stack for a student project with a React frontend, API backend, and relational database.",
    "question_text": "Which approach is most suitable?",
    "choice_a_text": "Select technologies that match the requirements and can be maintained by the team.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "A suitable stack should support the project needs and be understandable to the development team.",
    "choice_a_next_scenario_id": 93,
    "choice_b_text": "Select the most popular technology without considering the project.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Popularity can be useful, but it does not guarantee suitability for every project.",
    "choice_b_next_scenario_id": 93,
    "choice_c_text": "Use as many frameworks as possible to make the project advanced.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Unnecessary technologies increase complexity, maintenance effort, and possible integration problems.",
    "choice_c_next_scenario_id": 93,
    "is_active": true
  },
  {
    "id": 93,
    "domain": "Full Stack",
    "day_number": 3,
    "step_number": 1,
    "scenario_text": "You are creating the frontend structure for an internship portal. The application contains a navigation bar, dashboard, profile page, and task page.",
    "question_text": "How should you organize the frontend code?",
    "choice_a_text": "Create reusable components and organize pages, services, assets, and utilities clearly.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "A clean structure improves maintainability, reuse, debugging, and collaboration.",
    "choice_a_next_scenario_id": 94,
    "choice_b_text": "Place all JSX, styles, and API calls inside one large component.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "It may work initially, but the component becomes difficult to maintain as features increase.",
    "choice_b_next_scenario_id": 94,
    "choice_c_text": "Duplicate the same navigation and button code on every page.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Duplicated code creates inconsistency and makes future changes harder.",
    "choice_c_next_scenario_id": 94,
    "is_active": true
  },
  {
    "id": 94,
    "domain": "Full Stack",
    "day_number": 4,
    "step_number": 1,
    "scenario_text": "A login page must send user credentials to the backend and display the correct result to the user.",
    "question_text": "What is the correct frontend implementation?",
    "choice_a_text": "Validate the form, send an API request, handle loading and errors, and store the authentication result safely.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "A complete login flow must handle validation, network status, success, failure, and authentication state.",
    "choice_a_next_scenario_id": 95,
    "choice_b_text": "Send the request without validating input or handling errors.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "The request may work, but users will receive a poor experience when errors occur.",
    "choice_b_next_scenario_id": 95,
    "choice_c_text": "Store the password in frontend local storage for future login.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Passwords must never be stored in browser storage or exposed unnecessarily.",
    "choice_c_next_scenario_id": 95,
    "is_active": true
  },
  {
    "id": 95,
    "domain": "Full Stack",
    "day_number": 5,
    "step_number": 1,
    "scenario_text": "The backend team is designing APIs for creating, reading, updating, and deleting internship tasks.",
    "question_text": "Which API design is appropriate?",
    "choice_a_text": "Use clear resource-based endpoints with suitable HTTP methods and status codes.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Consistent REST-style APIs improve communication between frontend and backend teams.",
    "choice_a_next_scenario_id": 96,
    "choice_b_text": "Use one endpoint for every operation regardless of the HTTP method.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A single endpoint can work, but it reduces clarity and makes API behavior harder to understand.",
    "choice_b_next_scenario_id": 96,
    "choice_c_text": "Return HTTP 200 for every successful or failed request.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Correct status codes help clients identify validation, authentication, authorization, and server errors.",
    "choice_c_next_scenario_id": 96,
    "is_active": true
  },
  {
    "id": 96,
    "domain": "Full Stack",
    "day_number": 6,
    "step_number": 1,
    "scenario_text": "An API endpoint receives user registration data from the frontend. Some users submit missing or incorrectly formatted fields.",
    "question_text": "How should the backend handle the input?",
    "choice_a_text": "Validate all input fields on the backend before processing or storing the data.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Backend validation protects the application even when requests bypass frontend validation.",
    "choice_a_next_scenario_id": 97,
    "choice_b_text": "Trust the frontend validation completely.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Frontend validation improves user experience, but it cannot be the only security layer.",
    "choice_b_next_scenario_id": 97,
    "choice_c_text": "Save every request directly into the database.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Unvalidated data can cause incorrect records, security issues, and database errors.",
    "choice_c_next_scenario_id": 97,
    "is_active": true
  },
  {
    "id": 97,
    "domain": "Full Stack",
    "day_number": 7,
    "step_number": 1,
    "scenario_text": "The team is designing the database for users, domains, mentors, and internship tasks. Each user can be assigned to one domain.",
    "question_text": "What database design should you choose?",
    "choice_a_text": "Create normalized tables with primary keys and appropriate foreign-key relationships.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Proper relationships reduce duplication and maintain data consistency.",
    "choice_a_next_scenario_id": 98,
    "choice_b_text": "Store all user, mentor, and task information in one very large table.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A single table may be simple initially but often causes duplication and update problems.",
    "choice_b_next_scenario_id": 98,
    "choice_c_text": "Store relationship information only in frontend variables.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Important relationships must be stored and enforced by the backend and database.",
    "choice_c_next_scenario_id": 98,
    "is_active": true
  },
  {
    "id": 98,
    "domain": "Full Stack",
    "day_number": 8,
    "step_number": 1,
    "scenario_text": "A dashboard displays different data for interns, mentors, and administrators. A user reports seeing another domain's tasks.",
    "question_text": "What should you check first?",
    "choice_a_text": "Verify that the backend filters data using the authenticated user's role and domain assignment.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Authorization and domain filtering must be enforced on the backend, not only in the UI.",
    "choice_a_next_scenario_id": 99,
    "choice_b_text": "Hide the incorrect records using frontend conditions only.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Frontend filtering improves display but does not prevent unauthorized data access.",
    "choice_b_next_scenario_id": 99,
    "choice_c_text": "Give every user access to all records to avoid filtering errors.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Users should access only the records permitted by their role and assignment.",
    "choice_c_next_scenario_id": 99,
    "is_active": true
  },
  {
    "id": 99,
    "domain": "Full Stack",
    "day_number": 9,
    "step_number": 1,
    "scenario_text": "Your application uses JWT authentication. After login, the user can access the dashboard but should not access admin-only APIs.",
    "question_text": "How should the backend protect admin APIs?",
    "choice_a_text": "Verify the token and check the user's role before allowing access.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Authentication confirms identity, while authorization confirms whether the user has permission.",
    "choice_a_next_scenario_id": 100,
    "choice_b_text": "Allow access to anyone with a valid token.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A valid token alone does not prove that the user has administrator permissions.",
    "choice_b_next_scenario_id": 100,
    "choice_c_text": "Check the role only in the frontend menu.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Frontend controls can be bypassed, so authorization must be enforced on the server.",
    "choice_c_next_scenario_id": 100,
    "is_active": true
  },
  {
    "id": 100,
    "domain": "Full Stack",
    "day_number": 10,
    "step_number": 1,
    "scenario_text": "The frontend sends a request to the backend, but the browser blocks it because the frontend and backend use different origins.",
    "question_text": "What is the correct solution?",
    "choice_a_text": "Configure the backend CORS policy for the trusted frontend origin and required methods.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "CORS should be configured deliberately for the origins and requests that the application needs.",
    "choice_a_next_scenario_id": 101,
    "choice_b_text": "Allow every origin and every method permanently.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A broad policy may solve development issues but can create unnecessary security exposure.",
    "choice_b_next_scenario_id": 101,
    "choice_c_text": "Disable browser security settings for all users.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Users should not be asked to disable browser security to use a web application.",
    "choice_c_next_scenario_id": 101,
    "is_active": true
  },
  {
    "id": 101,
    "domain": "Full Stack",
    "day_number": 11,
    "step_number": 1,
    "scenario_text": "A task list page loads slowly because it requests hundreds of records even when the user only needs the first ten.",
    "question_text": "What improvement should you implement?",
    "choice_a_text": "Add backend pagination and request only the records required for the current page.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Pagination reduces response size, database work, and frontend rendering effort.",
    "choice_a_next_scenario_id": 102,
    "choice_b_text": "Load every record and hide most of them with CSS.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Hiding records does not reduce the data transferred or processed.",
    "choice_b_next_scenario_id": 102,
    "choice_c_text": "Increase the browser font size to improve performance.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Font size does not solve excessive API response size or database processing.",
    "choice_c_next_scenario_id": 102,
    "is_active": true
  },
  {
    "id": 102,
    "domain": "Full Stack",
    "day_number": 12,
    "step_number": 1,
    "scenario_text": "A search endpoint becomes slow when users search tasks by title and status. The database contains thousands of records.",
    "question_text": "What should you investigate?",
    "choice_a_text": "Review the query plan and add suitable database indexes for frequently filtered fields.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Query analysis and indexing can improve lookup performance when used appropriately.",
    "choice_a_next_scenario_id": 103,
    "choice_b_text": "Add indexes to every column without checking query usage.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Indexes can help reads but excessive indexes increase storage and write overhead.",
    "choice_b_next_scenario_id": 103,
    "choice_c_text": "Move all database records into frontend code.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Moving all data to the frontend is insecure, inefficient, and difficult to maintain.",
    "choice_c_next_scenario_id": 103,
    "is_active": true
  },
  {
    "id": 103,
    "domain": "Full Stack",
    "day_number": 13,
    "step_number": 1,
    "scenario_text": "A user submits a form twice because the first request appears slow. Two duplicate task records are created.",
    "question_text": "How can you prevent duplicate submissions?",
    "choice_a_text": "Disable repeated submission while processing and enforce suitable backend uniqueness or idempotency rules.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Both frontend protection and backend safeguards are needed for reliable duplicate prevention.",
    "choice_a_next_scenario_id": 104,
    "choice_b_text": "Only change the submit button color after clicking.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Visual changes do not prevent repeated requests or duplicate database records.",
    "choice_b_next_scenario_id": 104,
    "choice_c_text": "Allow duplicates and ask users to delete them later.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Duplicate data can affect reports, workflows, and business rules.",
    "choice_c_next_scenario_id": 104,
    "is_active": true
  },
  {
    "id": 104,
    "domain": "Full Stack",
    "day_number": 14,
    "step_number": 1,
    "scenario_text": "The frontend needs to show whether a task is loading, completed, failed, or empty.",
    "question_text": "What should the UI implement?",
    "choice_a_text": "Create clear loading, success, error, and empty states based on the API response.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Users need clear feedback for every stage of an asynchronous operation.",
    "choice_a_next_scenario_id": 105,
    "choice_b_text": "Show a blank page until the request finishes.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A blank page gives users no information about whether the application is working.",
    "choice_b_next_scenario_id": 105,
    "choice_c_text": "Display success even when the API request fails.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Incorrect success messages create trust and data consistency problems.",
    "choice_c_next_scenario_id": 105,
    "is_active": true
  },
  {
    "id": 105,
    "domain": "Full Stack",
    "day_number": 15,
    "step_number": 1,
    "scenario_text": "The backend returns an internal database error directly to the browser, including SQL details and file paths.",
    "question_text": "How should you handle backend errors?",
    "choice_a_text": "Log detailed errors securely on the server and return a safe, useful message to the client.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Server logs help debugging while safe client messages avoid exposing sensitive implementation details.",
    "choice_a_next_scenario_id": 106,
    "choice_b_text": "Return the complete stack trace to help every user.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Stack traces may help developers but can expose sensitive information to attackers.",
    "choice_b_next_scenario_id": 106,
    "choice_c_text": "Hide every error and return an empty response.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Users and developers need meaningful error handling to understand what happened.",
    "choice_c_next_scenario_id": 106,
    "is_active": true
  },
  {
    "id": 106,
    "domain": "Full Stack",
    "day_number": 16,
    "step_number": 1,
    "scenario_text": "A frontend page needs data from three APIs. The page should not display incomplete information as if everything loaded successfully.",
    "question_text": "What is a reliable approach?",
    "choice_a_text": "Track each request state and decide whether to show complete, partial, loading, or error content.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Independent request states make the UI accurate and resilient when one API fails.",
    "choice_a_next_scenario_id": 107,
    "choice_b_text": "Assume all APIs always succeed.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Assuming success causes broken displays when network or backend failures occur.",
    "choice_b_next_scenario_id": 107,
    "choice_c_text": "Use random placeholder values whenever an API fails.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Fake values can mislead users and hide actual system problems.",
    "choice_c_next_scenario_id": 107,
    "is_active": true
  },
  {
    "id": 107,
    "domain": "Full Stack",
    "day_number": 17,
    "step_number": 1,
    "scenario_text": "A mentor dashboard must update immediately after an intern submits an assessment. The current page shows old data until refresh.",
    "question_text": "What should you implement?",
    "choice_a_text": "Update local state after a confirmed submission and refetch or synchronize the affected backend data.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "The UI should reflect confirmed backend state without requiring an unnecessary full-page refresh.",
    "choice_a_next_scenario_id": 108,
    "choice_b_text": "Change only the displayed status without saving the submission.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Changing display state alone can become incorrect after refresh or another login.",
    "choice_b_next_scenario_id": 108,
    "choice_c_text": "Refresh the entire browser after every button click.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Full refreshes are inefficient and can hide synchronization problems in the application logic.",
    "choice_c_next_scenario_id": 108,
    "is_active": true
  },
  {
    "id": 108,
    "domain": "Full Stack",
    "day_number": 18,
    "step_number": 1,
    "scenario_text": "A developer stores API URLs, database passwords, and JWT secrets directly inside the source code repository.",
    "question_text": "What should the team do?",
    "choice_a_text": "Move secrets to environment variables or a secure secret manager and rotate exposed credentials.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Secrets should not be committed to source control and exposed credentials must be replaced.",
    "choice_a_next_scenario_id": 109,
    "choice_b_text": "Keep the secrets in code but make the variable names confusing.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Obscuring variable names does not protect credentials from repository access.",
    "choice_b_next_scenario_id": 109,
    "choice_c_text": "Publish the repository publicly so the team can collaborate easily.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Public repositories can expose credentials and create serious security risks.",
    "choice_c_next_scenario_id": 109,
    "is_active": true
  },
  {
    "id": 109,
    "domain": "Full Stack",
    "day_number": 19,
    "step_number": 1,
    "scenario_text": "An application accepts a task description that may contain HTML and script tags entered by users.",
    "question_text": "How should you protect the application?",
    "choice_a_text": "Validate input, encode output, sanitize allowed content, and avoid unsafe HTML rendering.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Multiple layers of input and output protection reduce cross-site scripting risks.",
    "choice_a_next_scenario_id": 110,
    "choice_b_text": "Trust all user-provided HTML because it comes from a logged-in user.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Authenticated users can still submit malicious content or compromised input.",
    "choice_b_next_scenario_id": 110,
    "choice_c_text": "Render every input using an unsafe HTML injection method.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Unsafe HTML rendering can execute malicious scripts in other users' browsers.",
    "choice_c_next_scenario_id": 110,
    "is_active": true
  },
  {
    "id": 110,
    "domain": "Full Stack",
    "day_number": 20,
    "step_number": 1,
    "scenario_text": "The team wants to upload internship certificates as PDF files. Users may try uploading executable files with a PDF extension.",
    "question_text": "What should the backend do?",
    "choice_a_text": "Validate file type, size, content, filename, storage location, and access permissions.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Secure file handling requires more than trusting the filename or extension.",
    "choice_a_next_scenario_id": 111,
    "choice_b_text": "Accept every file if the filename ends with .pdf.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "File extensions can be changed easily and do not prove the actual file type.",
    "choice_b_next_scenario_id": 111,
    "choice_c_text": "Store uploaded files in an executable public directory.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Unsafe storage can allow malicious files to be executed or accessed improperly.",
    "choice_c_next_scenario_id": 111,
    "is_active": true
  },
  {
    "id": 111,
    "domain": "Full Stack",
    "day_number": 21,
    "step_number": 1,
    "scenario_text": "Your application works correctly on a laptop but the dashboard is cut off on mobile devices and tablets.",
    "question_text": "What should you improve?",
    "choice_a_text": "Use responsive layouts, flexible dimensions, suitable breakpoints, and test across device sizes.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Responsive design ensures the application works across different screen sizes and orientations.",
    "choice_a_next_scenario_id": 112,
    "choice_b_text": "Set a fixed desktop width for every screen.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Fixed widths often cause overflow and unusable layouts on smaller screens.",
    "choice_b_next_scenario_id": 112,
    "choice_c_text": "Tell mobile users to zoom out until the page fits.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Users should not need to use awkward workarounds to access a responsive application.",
    "choice_c_next_scenario_id": 112,
    "is_active": true
  },
  {
    "id": 112,
    "domain": "Full Stack",
    "day_number": 22,
    "step_number": 1,
    "scenario_text": "A page contains many images and large JavaScript bundles. Users with slow internet experience long loading times.",
    "question_text": "Which optimization is suitable?",
    "choice_a_text": "Compress images, lazy-load noncritical content, split bundles, and minimize unnecessary requests.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Reducing asset size and loading only what is needed improves performance.",
    "choice_a_next_scenario_id": 113,
    "choice_b_text": "Add more animations to make loading feel faster.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Animations may improve appearance but do not reduce actual network or processing cost.",
    "choice_b_next_scenario_id": 113,
    "choice_c_text": "Load every image and script before showing any content.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Blocking all content until every asset loads increases perceived and actual loading time.",
    "choice_c_next_scenario_id": 113,
    "is_active": true
  },
  {
    "id": 113,
    "domain": "Full Stack",
    "day_number": 23,
    "step_number": 1,
    "scenario_text": "The application has repeated database queries inside a loop while displaying a list of tasks and their assigned mentors.",
    "question_text": "What problem might this create?",
    "choice_a_text": "It may create an N+1 query problem, so relationships should be loaded efficiently.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Reducing repeated queries improves database performance and response time.",
    "choice_a_next_scenario_id": 114,
    "choice_b_text": "It always improves performance because smaller queries are better.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Many repeated queries can be slower than one properly designed query.",
    "choice_b_next_scenario_id": 114,
    "choice_c_text": "Move the database queries into the browser.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Database access should remain protected behind the backend API.",
    "choice_c_next_scenario_id": 114,
    "is_active": true
  },
  {
    "id": 114,
    "domain": "Full Stack",
    "day_number": 24,
    "step_number": 1,
    "scenario_text": "A task submission updates several database tables, including submission status, leaderboard points, and attendance.",
    "question_text": "How should the backend process these updates?",
    "choice_a_text": "Use a database transaction so related changes succeed or roll back together.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Transactions preserve consistency when multiple related database changes are required.",
    "choice_a_next_scenario_id": 115,
    "choice_b_text": "Update each table separately without checking failures.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "A failure in the middle can leave inconsistent records.",
    "choice_b_next_scenario_id": 115,
    "choice_c_text": "Update only the frontend values and skip database changes.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Important business data must be persisted reliably in the backend database.",
    "choice_c_next_scenario_id": 115,
    "is_active": true
  },
  {
    "id": 115,
    "domain": "Full Stack",
    "day_number": 25,
    "step_number": 1,
    "scenario_text": "The frontend team changes the request field from `domain` to `domain_name`, causing the backend validation to fail.",
    "question_text": "How should the teams prevent this problem?",
    "choice_a_text": "Maintain documented API contracts and coordinate schema changes between frontend and backend.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Shared API contracts reduce integration errors and clarify expected request and response formats.",
    "choice_a_next_scenario_id": 116,
    "choice_b_text": "Allow frontend developers to guess the backend field names.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Guessing field names causes avoidable integration failures.",
    "choice_b_next_scenario_id": 116,
    "choice_c_text": "Rename fields randomly in both projects until the request works.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Random changes make the system harder to understand and can introduce additional bugs.",
    "choice_c_next_scenario_id": 116,
    "is_active": true
  },
  {
    "id": 116,
    "domain": "Full Stack",
    "day_number": 26,
    "step_number": 1,
    "scenario_text": "A team member modifies the authentication backend and wants to merge the changes into the shared branch.",
    "question_text": "What should happen before merging?",
    "choice_a_text": "Review the changes, run tests, resolve conflicts, and verify that existing features still work.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Code review and testing reduce the chance of introducing regressions into shared code.",
    "choice_a_next_scenario_id": 117,
    "choice_b_text": "Merge immediately because the code works on the developer's machine.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Local success does not guarantee compatibility with the complete application.",
    "choice_b_next_scenario_id": 117,
    "choice_c_text": "Delete the existing branch before reviewing the changes.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Deleting branches without review can cause loss of work and integration problems.",
    "choice_c_next_scenario_id": 117,
    "is_active": true
  },
  {
    "id": 117,
    "domain": "Full Stack",
    "day_number": 27,
    "step_number": 1,
    "scenario_text": "The application passes frontend tests but fails when the frontend communicates with the real backend and database.",
    "question_text": "What type of testing is required?",
    "choice_a_text": "Perform integration and end-to-end testing using realistic API and database workflows.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Integration and end-to-end tests verify that the complete application works together.",
    "choice_a_next_scenario_id": 118,
    "choice_b_text": "Run only isolated component tests.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Unit and component tests are useful but may not detect integration failures.",
    "choice_b_next_scenario_id": 118,
    "choice_c_text": "Skip testing because each individual file works.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Individual files can work while the complete workflow fails.",
    "choice_c_next_scenario_id": 118,
    "is_active": true
  },
  {
    "id": 118,
    "domain": "Full Stack",
    "day_number": 28,
    "step_number": 1,
    "scenario_text": "The application is ready for deployment. The frontend uses one API URL locally, but production requires a different backend URL.",
    "question_text": "What is the correct deployment approach?",
    "choice_a_text": "Use environment-specific configuration and verify production API, database, and security settings.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Separate configuration prevents local settings from being accidentally used in production.",
    "choice_a_next_scenario_id": 119,
    "choice_b_text": "Hardcode the local API URL in the production build.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "The production frontend may fail if it points to a local development server.",
    "choice_b_next_scenario_id": 119,
    "choice_c_text": "Use development database credentials in production.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Production must use secure, separate credentials and properly configured services.",
    "choice_c_next_scenario_id": 119,
    "is_active": true
  },
  {
    "id": 119,
    "domain": "Full Stack",
    "day_number": 29,
    "step_number": 1,
    "scenario_text": "After deployment, users report that some API requests fail randomly. The team needs to identify the cause.",
    "question_text": "What should you do?",
    "choice_a_text": "Check server logs, request traces, monitoring metrics, database health, and recent deployments.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "Systematic monitoring and logs help identify whether the issue is in the frontend, backend, database, or infrastructure.",
    "choice_a_next_scenario_id": 120,
    "choice_b_text": "Restart the server repeatedly without checking the cause.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Restarting may temporarily hide the issue but does not provide a reliable diagnosis.",
    "choice_b_next_scenario_id": 120,
    "choice_c_text": "Ignore the reports because the application worked during development.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "Production issues must be investigated because they affect real users and data.",
    "choice_c_next_scenario_id": 120,
    "is_active": true
  },
  {
    "id": 120,
    "domain": "Full Stack",
    "day_number": 30,
    "step_number": 1,
    "scenario_text": "You have completed a full stack internship portal with frontend pages, backend APIs, authentication, database integration, role-based access, and deployment.",
    "question_text": "What should you do before presenting the final project?",
    "choice_a_text": "Perform complete workflow testing, verify security and responsiveness, remove dummy data, and prepare documentation.",
    "choice_a_feedback_type": "Excellent",
    "choice_a_reason": "A final validation confirms that the application is functional, secure, responsive, integrated, and ready to demonstrate.",
    "choice_a_next_scenario_id": 120,
    "choice_b_text": "Present only the frontend screens without checking backend workflows.",
    "choice_b_feedback_type": "Good",
    "choice_b_reason": "Frontend screens are important, but a full stack project must demonstrate real backend and database integration.",
    "choice_b_next_scenario_id": 120,
    "choice_c_text": "Use mock responses during the presentation even though real APIs are incomplete.",
    "choice_c_feedback_type": "Needs Improvement",
    "choice_c_reason": "The final project should demonstrate the actual implemented functionality rather than hiding incomplete integration.",
    "choice_c_next_scenario_id": 120,
    "is_active": true
  }
]
"""

def main():
    db = SessionLocal()
    
    try:
        scenarios_data = json.loads(data_json)
        
        # We will insert them and let DB auto-generate IDs.
        # But we must preserve the next_scenario_id linkages.
        # Since they are inserted sequentially, we can insert them one by one or get their new IDs.
        # It's easiest to create them, commit, then update the references.
        
        id_mapping = {} # maps old JSON id to new DB id
        
        for item in scenarios_data:
            old_id = item.pop("id")
            
            # Remove created_at and updated_at if they are in the JSON
            item.pop("created_at", None)
            item.pop("updated_at", None)
            
            # Temporarily clear next_scenario_ids
            old_next_a = item.pop("choice_a_next_scenario_id", None)
            old_next_b = item.pop("choice_b_next_scenario_id", None)
            old_next_c = item.pop("choice_c_next_scenario_id", None)
            
            scenario = DailyScenario(**item)
            db.add(scenario)
            db.commit()
            
            new_id = scenario.id
            id_mapping[old_id] = {
                "new_id": new_id,
                "old_next_a": old_next_a,
                "old_next_b": old_next_b,
                "old_next_c": old_next_c
            }
            
        # Second pass: update the next_scenario_ids
        for old_id, mapping in id_mapping.items():
            new_id = mapping["new_id"]
            
            next_a = id_mapping.get(mapping["old_next_a"], {}).get("new_id") if mapping["old_next_a"] else None
            next_b = id_mapping.get(mapping["old_next_b"], {}).get("new_id") if mapping["old_next_b"] else None
            next_c = id_mapping.get(mapping["old_next_c"], {}).get("new_id") if mapping["old_next_c"] else None
            
            db.query(DailyScenario).filter(DailyScenario.id == new_id).update({
                "choice_a_next_scenario_id": next_a,
                "choice_b_next_scenario_id": next_b,
                "choice_c_next_scenario_id": next_c
            }, synchronize_session=False)
            
        db.commit()
        print(f"Successfully added {len(scenarios_data)} Full Stack scenarios to daily_scenarios table.")
            
    except Exception as e:
        db.rollback()
        print(f"Error seeding data: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    main()
