import React, { useState, useEffect } from 'react';
import { CheckCircle2, Circle } from 'lucide-react';
import { mockOnboardingService, ONBOARDING_STATUSES } from '../../services/mockOnboardingService';
import './Onboarding.css';

export default function Documents() {
    const [statusData, setStatusData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchStatus = async () => {
            setLoading(true);
            try {
                const result = await mockOnboardingService.getApplicationStatus();
                setStatusData(result);
            } catch (error) {
                console.error("Error fetching status", error);
            } finally {
                setLoading(false);
            }
        };
        fetchStatus();
    }, []);

    if (loading) {
        return <div className="onboarding-container">Loading document details...</div>;
    }

    if (!statusData) {
        return <div className="onboarding-container">Unable to load document details.</div>;
    }

    const { status, applicationId } = statusData;
    const documentsReady = [
        ONBOARDING_STATUSES.DOCUMENTS_GENERATED, 
        ONBOARDING_STATUSES.DOCUMENTS_SENT, 
        ONBOARDING_STATUSES.ACCOUNT_CREATION_PENDING,
        ONBOARDING_STATUSES.ACCOUNT_CREATED,
        ONBOARDING_STATUSES.ONBOARDING_COMPLETED
    ].includes(status);

    return (
        <div className="onboarding-container">
            <h2>Your Internship Documents</h2>
            <p style={{ marginBottom: '24px' }}>Access official offer letters, terms, and onboarding certificates.</p>

            {documentsReady ? (
                <div className="status-box">
                    <p style={{ marginBottom: '16px' }}><strong>Intern ID:</strong> INT-2026-{applicationId.split('-').pop()}</p>
                    
                    <div style={{ marginTop: '16px', padding: '16px', border: '1px solid #cbd5e1', borderRadius: '8px', background: '#ffffff' }}>
                        <h4 style={{ color: '#16a34a', margin: '0 0 4px 0', display: 'flex', alignItems: 'center', gap: '6px' }}><CheckCircle2 size={16} /> Internship Offer Letter</h4>
                        <p style={{ fontSize: '13px', color: '#64748b', margin: '0 0 12px 0' }}>Generated on: August 15, 2026</p>
                        <div className="button-group" style={{ justifyContent: 'flex-start', gap: '10px', marginTop: '0' }}>
                            <button type="button" onClick={() => alert("Viewing Offer Letter (Mock)")}>View</button>
                            <button type="button" onClick={() => alert("Downloading Offer Letter (Mock)")}>Download</button>
                        </div>
                    </div>

                    <div style={{ marginTop: '16px', padding: '16px', border: '1px solid #cbd5e1', borderRadius: '8px', background: '#ffffff' }}>
                        <h4 style={{ color: '#16a34a', margin: '0 0 4px 0', display: 'flex', alignItems: 'center', gap: '6px' }}><CheckCircle2 size={16} /> Terms & Conditions Agreement</h4>
                        <p style={{ fontSize: '13px', color: '#64748b', margin: '0 0 12px 0' }}>Generated on: August 15, 2026</p>
                        <div className="button-group" style={{ justifyContent: 'flex-start', gap: '10px', marginTop: '0' }}>
                            <button type="button" onClick={() => alert("Viewing T&C (Mock)")}>View</button>
                            <button type="button" onClick={() => alert("Downloading T&C (Mock)")}>Download</button>
                        </div>
                    </div>
                    
                    <button style={{ marginTop: '28px' }} onClick={() => window.location.href='/onboarding/status'}>Back to Status</button>
                </div>
            ) : (
                <div className="status-box">
                    <p style={{ marginBottom: '16px' }}>Your onboarding documents are currently being generated by administration.</p>
                    
                    <ul style={{ color: '#94a3b8', listStyleType: 'none', paddingLeft: '0', margin: '0 0 16px 0', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                        <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Circle size={14} /> Intern ID Assignment</li>
                        <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Circle size={14} /> Internship Offer Letter</li>
                        <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Circle size={14} /> Terms & Agreement Document</li>
                    </ul>
                    
                    <button style={{ marginTop: '12px' }} onClick={() => window.location.href='/onboarding/status'}>Back to Status</button>
                </div>
            )}
        </div>
    );
}
